DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS article;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE article (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uploader_id INTEGER NOT NULL,
  uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published TEXT NOT NULL,
  author TEXT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  sentiment TEXT NOT NULL,
  article_url TEXT NOT NULL,
  keyword TEXT NOT NULL,
  para_list TEXT NOT NULL,
  FOREIGN KEY (uploader_id) REFERENCES user (id)
);